# 檔案要放到 .github/workflows 底下, 副檔名 .yml
# 文件名稱
name: GitHub Actions Build and Deploy to gh-pages
# 觸發時機
on:
  push:
    branches:
      - main
# 執行工作列表
jobs:
  build-and-deploy:
    # 執行環境
    runs-on: ubuntu-latest
    # 執行步驟
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - uses: actions/cache@v2
        with:
          path: ~/.cache
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1

      - name: Use Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: v14
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install and Build
        run: |
          pnpm install
          pnpm dist:gh-pages
        env:
          VITE_API_ID: ${{ secrets.VITE_API_ID }}
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

      - name: Create 404.html
        run: cp dist/index.html dist/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          BRANCH: gh-pages
          FOLDER: dist
